version: '3'

services:
  message-service:
    image: message-service:latest
  user-service:
    image: user-service:latest
    command:
    - "--mysql.address=192.168.2.1"
    - "--mysql.port=3306"
  user-edge-service:
    image: user-edge-service:latest
    links:
    - message-service
    - user-service
    command:
    - "--redis.address=192.168.2.1"
    - "--redis.port=6379"
  course-service:
    image: course-service:latest
    links:
    - user-service
    command:
    - "--zookeeper.address=192.168.2.1"
    - "--mysql.address=192.168.2.1"
    - "--mysql.port=3306"
  course-edge-service:
    image: course-edge-service:latest
    links:
      - user-edge-service
    command:
    - "--zookeeper.address=192.168.2.1"
  api-gateway:
    image: api-gateway:latest
    links:
    - course-edge-service
    - user-edge-service
    ports:
    - 10000:10000