
thrift:
  type: win.hgfdodo.course.user.UserService.Client
  address: 127.0.0.1
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.20.13.24:3306/db_course?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hgfgood
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://10.20.13.24:2181
    protocol:
      name: dubbo
      port: 20880
    scan: win.hgfdodo.course.service