spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.20.13.24:3306/db_course
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hgfgood
  application:
    name: course-service
server:
  port: 6060