spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:${mysql.port}/db_user?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hgfgood
