spring:
  dubbo:
    application:
      name: edge-consumer
    registry:
      address: zookeeper://${zookeeper.address}:2181
    scan: win.hgfdodo.course.edge.controller
user:
  filter:
    user-edge-service: http://localhost:8888/user
    login-page: /login
    authentication: /authentication
