spring:
  dubbo:
    application:
      name: course-edge-service
    registry:
      address: zookeeper://${zookeeper.address}:2181
    scan: win.hgfdodo.course.edge.controller
user:
  filter:
    login-page: http://localhost:8888/user/login
    authentication: http://localhost:8888/user/authentication