spring:
  dubbo:
    application:
      name: course-edge-service
    registry:
      address: zookeeper://${zookeeper.address}:2181
    scan: win.hgfdodo.course.controller
user:
  filter:
    user-edge-service: http://127.0.0.1:10000/user
    login-page: /login
    authentication: /authentication
