user:
  type: win.hgfdodo.course.user.UserService.Client
  address: localhost
  port: 8080
message:
  type: win.hgfdodo.course.message.MessageService.Client
  address: 127.0.0.1
  port: 9090
#debug: true