user:
  type: win.hgfdodo.course.user.UserService.Client
  address: localhost
  port: 8080
message:
  type: win.hgfdodo.course.message.MessageService.Client
  address: 127.0.0.1
  port: 9090
spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
#debug: true