user:
  type: win.hgfdodo.course.user.UserService.Client
  address: user-service
  port: 8080
message:
  type: win.hgfdodo.course.message.MessageService.Client
  address: message-service
  port: 9090
spring:
  redis:
    host: ${redis.address}
    port: ${redis.port}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms